name: GitHub Actions Demo
on: [ push ]
jobs:
  pipiline:
    name: Skaffold Docker build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save b9a6d687-d0c9-4d9a-b7b4-308a7f7cc4a4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Skaffold
        run: sudo apt-get install google-cloud-sdk-skaffold
      - name: Deploy system
        run: skaffold run
