name: GitHub Actions Demo
on: [ push ]
jobs:
  pipiline:
    name: Skaffold Docker build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.12.0
        with:
          command: run
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: echo "ajojo"
      - run: docker --version
      - run: docker images
